```{r setup, include=FALSE}
library(here)
library(scales)
library(tidyverse)
library(ggplot2)
library(stringr)

knitr::opts_chunk$set(echo = TRUE)
```


```{r load data}
notes <- read_tsv("Data/notes.tsv")
view(notes)

ratings <- read_tsv("Data/ratings.tsv")
view(ratings)

notes_with_ratings <- left_join(notes, ratings, by = "noteId") 

view(notes_with_ratings)

max(ratings$createdAtMillis)
max(notes$createdAtMillis)


n_distinct(notes_with_ratings$noteId)

```

```{r work on Figure 2, fig.width=4, fig.height=4}
n_distinct(notes_with_ratings$classification) # to make sure what are the possible options for this column 

work_figure_2 <- notes_with_ratings |> group_by(classification, trustworthySources) |> summarise(count = n_distinct(noteId))
view(work_figure_2)

# change levels of trustworthySources (0,1) to (Trustworthy Sources, No trustworthy Sources) then order the levels for the graph 
work_figure_2 <- work_figure_2 |> mutate(
    trustworthySources = factor(trustworthySources, levels = c(1,0), labels =  c("Trustworthy Sources" , "No trustworthy Sources"))
) 
work_figure_2$trustworthySources <- factor(work_figure_2$trustworthySources, levels = c("No trustworthy Sources", "Trustworthy Sources"))


# Change column classification to factor from chr then order the levels for the graph
work_figure_2$classification <- as.factor(work_figure_2$classification)
work_figure_2$classification <- factor(work_figure_2$classification, levels = c("NOT_MISLEADING", "MISINFORMED_OR_POTENTIALLY_MISLEADING"))


# plot the graph 
work_figure_2 |> ggplot(aes(x =  count, y = classification, fill = trustworthySources)) +
geom_bar(stat = "identity", width = 0.1) + 
scale_fill_manual(
    values = c("No trustworthy Sources" = "yellow", "Trustworthy Sources" = "#4141db")) + 
labs(
    x = "Number of Users", 
    y = "Classification", 
    fill = "Trustworthy Sources"
)
```


```{r work on Figure 3, fig.width=4, fig.height=4}

view(notes_with_ratings)

work_figure_3 <- notes_with_ratings |> filter(classification == "MISINFORMED_OR_POTENTIALLY_MISLEADING")

work_figure_3 <- work_figure_3 |> 
select(noteId, 
    misleadingFactualError, 
    misleadingMissingImportantContext,
    misleadingUnverifiedClaimAsFact, 
    misleadingOutdatedInformation, 
    misleadingOther, 
    misleadingSatire, 
    misleadingManipulatedMedia) 

work_figure_3 <- work_figure_3 |> pivot_longer(cols = -noteId, names_to = "Reason", values_to = "Flag")

work_figure_3 <-  work_figure_3 |> filter(Flag == 1)
work_figure_3 <- work_figure_3 |> group_by(Reason) |> summarise(Number_Notes = n_distinct(noteId))

work_figure_3 |> ggplot(aes(x = Number_Notes, y = reorder(Reason, Number_Notes))) +
geom_bar(stat = "identity", fill = "red", width = 0.2) + 
labs(
    x = "Number of Birdwatch Notes", 
    y = "Reason"
)



```


```{r work Figure 4, fig.width=4, fig.height=4}

view(notes)


work_figure_4 <- notes_with_ratings |> filter(classification == "NOT_MISLEADING")

work_figure_4 <- work_figure_4 |> 
select(
    noteId,
    notMisleadingOther, 
    notMisleadingFactuallyCorrect, 
    notMisleadingOutdatedButNotWhenWritten, 
    notMisleadingClearlySatire, 
    notMisleadingPersonalOpinion, 
    )
work_figure_4 <- work_figure_4 |> pivot_longer(cols = -noteId, names_to = "Reason", values_to = "Flag")
work_figure_4 <- work_figure_4 |> filter(Flag == 1)
work_figure_4 <- work_figure_4|> group_by(Reason) |> summarise(Number_Notes = n_distinct(noteId))

view(work_figure_4)

work_figure_4 |> ggplot(aes(x = Number_Notes, y = reorder(Reason, Number_Notes))) +
geom_bar(stat = "identity", fill = "#0e0e6b", width = 0.2) + 
labs(
    x = "Number of Birdwatch Notes", 
    y = "Reason"
)

```

```{r work Figure 5C, fig.width=4, fig.height=4}
view(notes)

work_figure_5_c <- notes_with_ratings |> distinct(noteId, .keep_all = TRUE)
work_figure_5_c <- work_figure_5_c |> mutate(wordcount = str_count(summary, boundary("word")))
work_figure_5_c <- work_figure_5_c |> group_by(classification) |> arrange(wordcount) |> 
mutate(
    rank = row_number(), 
    n = n(), 
    CCDF = 1- (rank-1) /n)

    # (rank-1) /n  ==> the fraction of the tweets that have wordcount smaller than the current 

view(work_figure_5_c)


work_figure_5_c |> ggplot(aes(x = wordcount, y = CCDF, color = classification)) + 
geom_line() + 
scale_y_log10(
    labels = scales::percent_format(accuracy = 0.01), 
    breaks = c(0.0001, 0.001, 0.01, 0.1, 1)
    )
```

```{r figure-7a, fig.width=4, fig.height=4}
work_figure_7a_misleading <- notes_with_ratings |>
    filter(classification == "MISINFORMED_OR_POTENTIALLY_MISLEADING") |>
    group_by(noteId) |>
    summarize(helpful_count = sum(helpful), votes_count = n()) |>
    mutate(helpful_ratio = helpful_count / votes_count) |>
    arrange(helpful_ratio) |>
    count(helpful_ratio) |>
    arrange(desc(helpful_ratio)) |>
    mutate(cummulative = cumsum(n), classification = "MISINFORMED_OR_POTENTIALLY_MISLEADING")

work_figure_7a_not_misleading <- notes_with_ratings |>
    filter(classification == "NOT_MISLEADING") |>
    group_by(noteId) |>
    summarize(helpful_count = sum(helpful), votes_count = n()) |>
    mutate(helpful_ratio = helpful_count / votes_count) |>
    arrange(helpful_ratio) |>
    count(helpful_ratio) |>
    arrange(desc(helpful_ratio)) |>
    mutate(cummulative = cumsum(n), classification = "NOT_MISLEADING")

work_figure_7a <- bind_rows(work_figure_7a_misleading, work_figure_7a_not_misleading)

work_figure_7a_CCDF <- work_figure_7a |>
    group_by(classification) |>
    summarize(helpful_ratio, CCDF = cummulative / max(cummulative)) |>
    arrange(classification, helpful_ratio)

View(work_figure_7a_CCDF)

work_figure_7a_CCDF |> ggplot(aes(x = helpful_ratio, y = CCDF, color = classification)) +
    geom_line() +
    scale_y_log10(
        labels = scales::percent_format()
    )
```

```{r figure-7b, fig.width=4, fig.height=4}
figure_7b_not_misleading <- notes_with_ratings |>
    filter(classification == "NOT_MISLEADING") |>
    group_by(noteId) |>
    summarize(votes_count = n()) |>
    arrange(desc(votes_count)) |>
    mutate(
        cummulative = cumsum(votes_count),
        CCDF = cummulative / max(cummulative),
        classification = "NOT_MISLEADING"
    )

figure_7b_misleading <- notes_with_ratings |>
    filter(classification == "MISINFORMED_OR_POTENTIALLY_MISLEADING") |>
    group_by(noteId) |>
    summarize(votes_count = n()) |>
    arrange(desc(votes_count)) |>
    mutate(
        cummulative = cumsum(votes_count),
        CCDF = cummulative / max(cummulative),
        classification = "MISLEADING"
    )

figure_7b <- bind_rows(figure_7b_misleading, figure_7b_not_misleading)

figure_7b |> ggplot(aes(x = votes_count, y = CCDF, color = classification)) +
    geom_line(size = 2) +
    scale_y_log10(
        labels = scales::percent_format(),
        breaks = c(0.0001, 0.001, 0.01, 0.1, 1)
    )
```

```{r figure_8, fig.width=4, fig.height=4}
figure_8_helpful <- notes_with_ratings |>
    filter(classification == "MISINFORMED_OR_POTENTIALLY_MISLEADING") |>
    select(
        noteId,
        helpfulOther,
        helpfulInformative,
        helpfulClear,
        helpfulEmpathetic,
        helpfulGoodSources,
        helpfulUniqueContext,
        helpfulAddressesClaim,
        helpfulImportantContext,
    )

figure_8_longer <- figure_8_helpful |> pivot_longer(cols = -noteId, names_to = "Reason", values_to = "Flag")

figure_8_longer <- figure_8_longer |> filter(Flag == 1)
figure_8_longer <- figure_8_longer |>
    group_by(Reason) |>
    summarise(Number_Notes = n_distinct(noteId))

figure_8_longer |> ggplot(aes(x = Number_Notes, y = reorder(Reason, Number_Notes))) +
    geom_bar(stat = "identity", fill = "blue", width = 0.2) +
    labs(
        x = "Number of Birdwatch Notes",
        y = "Reason"
    )
```

```{r figure-9, fig.width=4, fig.height=4}
figure_9_helpful <- notes_with_ratings |>
    filter(classification == "NOT_MISLEADING") |>
    select(
        noteId,
        notHelpfulSourcesMissingOrUnreliable,
        notHelpfulOpinionSpeculationOrBias,
        notHelpfulMissingKeyPoints,
        notHelpfulArgumentativeOrBiased,
        notHelpfulIncorrect,
        notHelpfulOffTopic,
        notHelpfulOther,
        notHelpfulHardToUnderstand,
        notHelpfulSpamHarassmentOrAbuse,
        notHelpfulOutdated,
        notHelpfulIrrelevantSources,
    )

figure_9_longer <- figure_9_helpful |> pivot_longer(cols = -noteId, names_to = "Reason", values_to = "Flag")

figure_9_longer <- figure_9_longer |> filter(Flag == 1)
figure_9_longer <- figure_9_longer |>
    group_by(Reason) |>
    summarise(Number_Notes = n_distinct(noteId))

figure_9_longer |> ggplot(aes(x = Number_Notes, y = reorder(Reason, Number_Notes))) +
    geom_bar(stat = "identity", fill = "blue", width = 0.2) +
    labs(
        x = "Number of Birdwatch Notes",
        y = "Reason"
    )
```



